//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHD
    {
        public int ID { get; set; }
        public string MaHD { get; set; }
        public string MaSP { get; set; }
        public int SLuong { get; set; }
        public decimal TongTien { get; set; }
        public int TrangThai { get; set; }
    
        public virtual DSHoaDon DSHoaDon { get; set; }
    }
}
