//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSThuongHieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DSThuongHieu()
        {
            this.DanhSachSPhs = new HashSet<DanhSachSPh>();
        }
    
        public string MaThuongHieu { get; set; }
        public string TenTh { get; set; }
        public string XuatXu { get; set; }
        public string DanhGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhSachSPh> DanhSachSPhs { get; set; }
    }
}
